const fs = require('fs');
const path = require('path');

const setsTest = [
"const request = require('supertest');",
"const express = require('express');",
"const setsRouter = require('../routes/sets');",
"const authRouter = require('../routes/auth');",
"const app = express();",
"app.use(express.json());",
"app.use('/auth', authRouter);",
"app.use('/sets', setsRouter);",
"let adminToken;",
"beforeAll(async () => {",
"  const res = await request(app).post('/auth/login').send({ email: 'admin@shiny.com', password: 'password123' });",
"  adminToken = res.body.token;",
"});",
"describe('Sets API', () => {",
"  test('GET /sets returns 200 and an array', async () => {",
"    const res = await request(app).get('/sets');",
"    expect(res.statusCode).toBe(200);",
"    expect(Array.isArray(res.body)).toBe(true);",
"  });",
"  test('GET /sets/:id returns 404 for nonexistent set', async () => {",
"    const res = await request(app).get('/sets/99999');",
"    expect(res.statusCode).toBe(404);",
"  });",
"  test('POST /sets returns 401 without token', async () => {",
"    const res = await request(app).post('/sets').send({ name: 'Test', setCode: 'TST', series: 'Test', totalCards: 100, releaseDate: '2024-01-01' });",
"    expect(res.statusCode).toBe(401);",
"  });",
"  test('POST /sets returns 201 with admin token', async () => {",
"    const res = await request(app).post('/sets').set('Authorization', 'Bearer ' + adminToken).send({ name: 'Test Set ' + Date.now(), setCode: 'TS' + Date.now(), series: 'Test', totalCards: 100, releaseDate: '2024-01-01' });",
"    expect(res.statusCode).toBe(201);",
"    expect(res.body).toHaveProperty('id');",
"  });",
"});",
].join('\n');

const cardsTest = [
"const request = require('supertest');",
"const express = require('express');",
"const cardsRouter = require('../routes/cards');",
"const setsRouter = require('../routes/sets');",
"const authRouter = require('../routes/auth');",
"const app = express();",
"app.use(express.json());",
"app.use('/auth', authRouter);",
"app.use('/sets', setsRouter);",
"app.use('/cards', cardsRouter);",
"let adminToken;",
"beforeAll(async () => {",
"  const res = await request(app).post('/auth/login').send({ email: 'admin@shiny.com', password: 'password123' });",
"  adminToken = res.body.token;",
"});",
"describe('Cards API', () => {",
"  test('GET /cards returns 200 and an array', async () => {",
"    const res = await request(app).get('/cards');",
"    expect(res.statusCode).toBe(200);",
"    expect(Array.isArray(res.body)).toBe(true);",
"  });",
"  test('GET /cards/:id returns 404 for nonexistent card', async () => {",
"    const res = await request(app).get('/cards/99999');",
"    expect(res.statusCode).toBe(404);",
"  });",
"  test('POST /cards returns 401 without token', async () => {",
"    const res = await request(app).post('/cards').send({ name: 'Bulbasaur', cardNumber: '001/198', rarity: 'Common', type: 'Grass', artist: 'Test', setId: 1 });",
"    expect(res.statusCode).toBe(401);",
"  });",
"  test('POST /cards returns 201 with admin token', async () => {",
"    const setRes = await request(app).post('/sets').set('Authorization', 'Bearer ' + adminToken).send({ name: 'Test Set ' + Date.now(), setCode: 'TC' + Date.now(), series: 'Test', totalCards: 100, releaseDate: '2024-01-01' });",
"    const res = await request(app).post('/cards').set('Authorization', 'Bearer ' + adminToken).send({ name: 'Bulbasaur', cardNumber: '001/198', rarity: 'Common', type: 'Grass', artist: 'Mitsuhiro Arita', setId: setRes.body.id });",
"    expect(res.statusCode).toBe(201);",
"    expect(res.body).toHaveProperty('id');",
"  });",
"});",
].join('\n');

const collectionsTest = [
"const request = require('supertest');",
"const express = require('express');",
"const collectionsRouter = require('../routes/collections');",
"const authRouter = require('../routes/auth');",
"const app = express();",
"app.use(express.json());",
"app.use('/auth', authRouter);",
"app.use('/collections', collectionsRouter);",
"let userToken;",
"beforeAll(async () => {",
"  const res = await request(app).post('/auth/login').send({ email: 'user@shiny.com', password: 'password123' });",
"  userToken = res.body.token;",
"});",
"describe('Collections API', () => {",
"  test('GET /collections returns 401 without token', async () => {",
"    const res = await request(app).get('/collections');",
"    expect(res.statusCode).toBe(401);",
"  });",
"  test('GET /collections returns 200 with token', async () => {",
"    const res = await request(app).get('/collections').set('Authorization', 'Bearer ' + userToken);",
"    expect(res.statusCode).toBe(200);",
"    expect(Array.isArray(res.body)).toBe(true);",
"  });",
"  test('POST /collections returns 401 without token', async () => {",
"    const res = await request(app).post('/collections').send({ name: 'Test Binder' });",
"    expect(res.statusCode).toBe(401);",
"  });",
"  test('POST /collections returns 201 with token', async () => {",
"    const res = await request(app).post('/collections').set('Authorization', 'Bearer ' + userToken).send({ name: 'Test Binder ' + Date.now() });",
"    expect(res.statusCode).toBe(201);",
"    expect(res.body).toHaveProperty('id');",
"  });",
"});",
].join('\n');

fs.writeFileSync(path.join(__dirname, '../tests/sets.test.js'), setsTest);
fs.writeFileSync(path.join(__dirname, '../tests/cards.test.js'), cardsTest);
fs.writeFileSync(path.join(__dirname, '../tests/collections.test.js'), collectionsTest);
console.log('All test files written successfully!');